name: intro_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9    # Recent stable version of Python
  - pip           # Used to download and install packages
  - jupyter       # A simple code editor
  - jupyterlab    # A more advanced code editor
  - ipykernel     # How the code editor accesses this collection of software packages
  - numpy         # "Numerical Python" - numerical methods
  - scipy         # "Scientific Python" - more numerical methods
  - pandas        # Data wrangling, spreadsheet like
  - openpyxl      # Needed to open xls files in Pandas
  - matplotlib    # Primary plotting package
  - seaborn       # Advanced static plotting package
  - plotly        # Advanced dynamic plotting package
  - pip:
    - xlrd==2.0.1 # Used to read xls files
    - chemicals   # Steam tables (and lots of other stuff for reservoir and process engineering)